server {
    listen 3000;
    server_name _;
    root /app;
    charset utf-8;

    # The main entry point has a special character in its name
    index "▶ Begin hier.html";

    location / {
        try_files $uri $uri/ /▶\ Begin\ hier.html;
    }
}
